modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Mozilla Public License 2.0"

[[mods]] #mandatory
modId="pvzreborn" #mandatory
version="${file.jarVersion}" #mandatory
displayName="PVZ:Reborn" #mandatory
#credits="" #optional
authors="XStudio" #optional
description=""
