modLoader="javafml"
loaderVersion="[40,)"
license="Mozilla Public License 2.0"
#logoFile=""

[[mods]] #mandatory
modId="pvzreborn" #mandatory
version="${file.jarVersion}" #mandatory
displayName="PVZ:Reborn" #mandatory
#credits="" #optional
authors="XStudio" #optional
description='''
'''
[[dependencies.pvzreborn]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.pvzreborn]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
